<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU4LYSKn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU4LYSKn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU4LYSKn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU4LYSKn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU4LYSKn\App_KernelDevDebugContainer([
    'container.build_hash' => 'U4LYSKn',
    'container.build_id' => 'eb44d2c4',
    'container.build_time' => 1707987479,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU4LYSKn');
