<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_evento' => [[], ['_controller' => 'App\\Controller\\EventoController::index'], [], [['text', '/evento']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\GrupoController::home'], [], [['text', '/']], [], [], []],
    'app_grupo' => [[], ['_controller' => 'App\\Controller\\GrupoController::index'], [], [['text', '/grupo']], [], [], []],
    'grupo_api' => [[], ['_controller' => 'App\\Controller\\GrupoController::indice'], [], [['text', '/grupo_api']], [], [], []],
    'app_noticia' => [[], ['_controller' => 'App\\Controller\\NoticiaController::index'], [], [['text', '/noticia']], [], [], []],
    'pagos_form' => [[], ['_controller' => 'App\\Controller\\NoticiaController::pagos'], [], [['text', '/pruebanoticia']], [], [], []],
    'project_index' => [[], ['_controller' => 'App\\Controller\\NoticiaController::indice'], [], [['text', '/projects']], [], [], []],
    'app_releventogrupo' => [[], ['_controller' => 'App\\Controller\\ReleventogrupoController::index'], [], [['text', '/releventogrupo']], [], [], []],
    'app_releventousuario' => [[], ['_controller' => 'App\\Controller\\ReleventousuarioController::index'], [], [['text', '/releventousuario']], [], [], []],
    'app_usuario' => [[], ['_controller' => 'App\\Controller\\UsuarioController::index'], [], [['text', '/usuario']], [], [], []],
];
