<?php

namespace ContainerX7GQ3um;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNoticiaControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\NoticiaController' shared autowired service.
     *
     * @return \App\Controller\NoticiaController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/NoticiaController.php';

        $container->services['App\\Controller\\NoticiaController'] = $instance = new \App\Controller\NoticiaController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\NoticiaController', $container));

        return $instance;
    }
}
