<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Evento extends \App\Entity\Evento implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'fecha' => [parent::class, 'fecha', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'nombre' => [parent::class, 'nombre', null],
        "\0".parent::class."\0".'numeroparticipantes' => [parent::class, 'numeroparticipantes', null],
        "\0".parent::class."\0".'relGrupoEventos' => [parent::class, 'relGrupoEventos', null],
        "\0".parent::class."\0".'relUsuarioEventos' => [parent::class, 'relUsuarioEventos', null],
        'fecha' => [parent::class, 'fecha', null],
        'id' => [parent::class, 'id', null],
        'nombre' => [parent::class, 'nombre', null],
        'numeroparticipantes' => [parent::class, 'numeroparticipantes', null],
        'relGrupoEventos' => [parent::class, 'relGrupoEventos', null],
        'relUsuarioEventos' => [parent::class, 'relUsuarioEventos', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
